### ISSUE TITLE
Don't use debug.*/Don't be bash

### ISSUE THREAD

**Issue by SoniEx2** [pkulchenko/serpent#15]
https://github.com/MinecraftPackageManager/ccapi/blob/master/src/rom/apis/textutils.lua#L214-L245

This should be ok, unless I'm missing something... (it should also be safer than debug hooks, as you can't "bash" it with a someglobal = function() _G.stuff() end)

**Comment by pkulchenko** [comment]
@SoniEx2, I checked in a hybrid fix for this. Give it a try and let me know if you find any holes. Thanks!
