### ISSUE TITLE
When keys are tables, `__serialize` is not called

### ISSUE THREAD

**Issue by saucisson** [pkulchenko/serpent#16]
In the example below:

```
local serpent = require "serpent"
local mt = {}
function mt.__serialize (x)
  return x.a
end
local d1 = setmetatable ({ a = 1 }, mt)
local d2 = setmetatable ({ a = 2 }, mt)
local data = { [d1] = d2 }
print (serpent.dump (data, {}))
```

the output is:

```
do local _={};local __={};__._table1=1;_[__._table1]=2;return _;end
```

As there is the same metatable for `d1` and `d2`, it can seem reasonable to apply the `__serialize` method to both the key and the value within `data`. The result would then be:

```
do local _={[1]=2};return _;end
```

See commit saucisson/serpent@3734d8f1422de9bc3d18390481375ee499a5a8af for a quick fix.

**Comment by pkulchenko** [comment]
Alban, good point. I'll probably apply a fix similar to yours, but I'm working on a patch that allow `__serilalize` and `__tostring` methods to return 'raw' results, so it's likely to affect that fragment as well. Need to think about it.

**Comment by pkulchenko** [comment]
I slightly modified the example and I do see `__serialize` to be called for both the value and the key:

```lua
local serpent = require "serpent"
local mt1 = {}
function mt1.__serialize (x)
  return x.a
end
local mt2 = {}
function mt2.__serialize (x)
  return x.a
end
local d1 = setmetatable ({ a = 1 }, mt1)
local d2 = setmetatable ({ a = 2 }, mt2)
local data = { [d1] = d2 }
print (serpent.dump (data, {}))
```

I don't have access to re-test your patch, but it's possible that one of the earlier changes has fixed this issue. This is probably not as compact as your representation, but it does seem to produce the correct result.
