### ISSUE TITLE
preserve floating point precision

### ISSUE THREAD

**Issue by cohadar** [pkulchenko/serpent#17]
This serializer does not preserve floating point precision
Lua uses double-precision floating-point numbers (17 decimals mantissa)

So please print them with either
string.format(“%1.16e”, d); // Round-trippable double, always with an exponent
or
string.format(“%.17g”, d); // Round-trippable double, shortest possible

For more details look here:
https://randomascii.wordpress.com/2012/03/08/float-precisionfrom-zero-to-100-digits-2/

**Comment by pkulchenko** [comment]
@cohadar, thank you for the suggestion. Do you have specific numbers in mind that would be good for round-trip testing (fails without the format, but works with the format)?

**Comment by cohadar** [comment]
No specific numbers in mind, but here is a little test.

	local text = string.format("%1.16e", math.pi)
	local pi1 = tonumber( text )
	assert( math.pi == pi1 )

	local text = string.format("%1.17g", math.pi)
	local pi2 = tonumber( text )
	assert( math.pi == pi2 )

	local text = serpent.line( { pi = math.pi } )
	ok, t = serpent.load( text )
	assert( ok )
	assert( math.pi == t.pi )

**Comment by pkulchenko** [comment]
Looks good. I'll probably set `%.17g` as the default and provide `numformat` as the option to change if needed.

**Comment by cohadar** [comment]
Great.
In case you were wondering I am using serpent for multiplayer game communication.
When numbers don't match on client and server you get frequent resyncs.

**Comment by pkulchenko** [comment]
@cohadar, pushed the changes; take a look. Thank you.

**Comment by oniietzschan** [comment]
Hey, sorry for the necro-post. I updated from v0.28 to v0.30 and noticed this behavior.

```lua
local SerpentOld = require 'serpent28'
local SerpentNew = require 'serpent30'
print(SerpentOld.block(0.5001)) -- prints: 0.5001
print(SerpentNew.block(0.5001)) -- print: 0.50009999999999999
```

I'm not asking for this to behavior to changed or reversed, since I see the benefit of the new format. I just thought I'd raise this, since I found it confusing at first.

Perhaps you could add a note to "numformat" suggesting to use `%.16g` if one doesn't want this "noise" added to their float? (however technically accurate it might be!)

**Comment by pkulchenko** [comment]
Good point; updated the documentation. Thanks for the suggestion!
