### ISSUE TITLE
bad argument #1 to 'pairs' (table expected, got boolean)

### ISSUE THREAD

**Issue by Pranz** [pkulchenko/serpent#20]
Using lua 5.1.5, the code `local serpent = require('serpent')` raises the following error:
```
Error: /usr/share/lua/5.1/serpent.lua:11: bad argument #1 to 'pairs' (table expected, got boolean)
stack traceback:
	[C]: in function 'pairs'
	/usr/share/lua/5.1/serpent.lua:11: in main chunk
	[C]: in function 'require'
	logic/action.lua:2: in main chunk
```

**Comment by pkulchenko** [comment]
@Pranz, what version of Serpent are you using? The current version has the following on line 11, which can't cause this error (and it doesn't with Lua 5.1.5): `for _,g in ipairs({'coroutine', 'debug', 'io', 'math', 'string', 'table', 'os'}) do`.

**Comment by Pranz** [comment]
I used the version on luarocks.org, 0.27-1. Installed the one from github now and that worked fine, so thanks for the help! It might be a good idea to bumb the version on luarocks?

**Comment by pkulchenko** [comment]
@Pranz, hm, luarocks should have 0.28: https://luarocks.org/modules/paulclinger/serpent/0.28-1. Does it not download it for you? I updated it a while ago.

Also, what environment/framework do you load it *from*?
