### ISSUE TITLE
Is serpent.load really safe?

### ISSUE THREAD

**Issue by Dafoosa** [pkulchenko/serpent#22]
The following code appears to hang the serpent.load() method:
local ok, t = serpent.load("{[(function() while true do end return 123 end)()] = 456}")

**Comment by pkulchenko** [comment]
Yes, there is no code in Serpent to protect from this, so if you are concerned about it, you should be using sandbox with some container support to limit CPU/resource utilization.

**Comment by pkulchenko** [comment]
For a simple mechanism to avoid running function, something like the following can be used:

```lua
local function loadsafe(data)
  local f, err = load(data)
  if not f then return f, err end
  local c = -2
  local hf, hm, hc = debug.gethook()
  debug.sethook(function() c=c+1; if c>0 then error("failed safety check") end end, "c")
  local ok, res = pcall(f)
  c = -1
  debug.sethook(hf, hm, hc)
  return ok, res
end
local ok, t = assert(loadsafe("return {[(function() while true do end return 123 end)()] = 456}"))
```

It should throw "failed safety check" error.

**Comment by Dafoosa** [comment]
The above code looks really good! Commnts: While the loadsafe() func still allows function declaration, so long as this is documented I see no concern here. Also, I suggest resetting the debug hook just prior before the call to error() in the event the caller invokes loadsafe() with a pcall(), the debug hook wont remain stuck on.

**Comment by pkulchenko** [comment]
> I suggest resetting the debug hook just prior before the call to error() in the event the caller invokes loadsafe() with a pcall(), the debug hook wont remain stuck on.

But that would be still handled by the `pcall` inside `loadsafe`, no? Do you have an example where the second (restoring) `sethook` is not being called?

**Comment by pkulchenko** [comment]
BTW, here is a more refined version:

```lua
local function loadsafe(data,opts)
  local f, res = (loadstring or load)('return '..data)
  if not f then f, res = (loadstring or load)(data) end
  if not f then return f, res end
  if opts and opts.safe == false then return pcall(f) end
  
  local c, thread = -2, coroutine.running()
  local hf, hm, hc = debug.gethook(thread)
  debug.sethook(function() c=c+1; if c>0 then error("failed safety check") end end, "c")
  res = {pcall(f)}
  c = -1 -- set again, otherwise it's tripped on the next sethook
  debug.sethook(thread, hf, hm, hc)
  return (table.unpack or unpack)(res)
end
```

Also see #9 and #15 for previous discussions. The difference between this one and the one in the current version is that the one in the current version allows anonymous functions to be called and this one doesn't. It may be worth switching to this one, even though the warning still remains.
