### ISSUE TITLE
Quadratic performance on large tables

### ISSUE THREAD

**Issue by estansifer** [pkulchenko/serpent#23]
I noticed that Serpent uses '..' for string concatenation which results in quadratic performance for serializing large tables. I noticed this when working with tables with on the order of 10^5 to 10^6 entries. By using table.concat instead the library should give linear performance; see [this](https://www.lua.org/pil/11.6.html) for an explanation of what I have in mind.

From a brief look at their source codes, it looks like penlight, nucleo, and metalua use table.concat so it may be possible to see a performance difference by changing the benchmark to use a table with many more elements.

Thanks

**Comment by estansifer** [comment]
Looking more closely it seems I am mostly wrong, so I am closing this issue.

It is true that I had super-linear performance (I am not going to assert that it was necessarily quadratic, but it was definitely slower than linear) with increasing table size. Looking at the '..' operators in the code made me believe that that was the culprit, but now I don't know what is. In any case I would be interested in seeing the benchmark extended to look at the serialization of large tables.

(Looking at the code, I suspect that deeply nested tables could produce actual quadratic performance, as it appears to result in nested table.concat(... table.concat(...) ...) calls, but that was not the case I was using.)

**Comment by pkulchenko** [comment]
@estansifer, I would not expect quadratic performance, but I do have an alternative processing that should be noticeably faster, but with the cost of not supporting most of the features, including multi/self-reference detection. You can give it a try to see if it works faster in your case:

```lua
local function plaindump(val, opts, done)
  local keyignore = opts and opts.keyignore or {}
  local final = done == nil
  opts, done = opts or {}, done or {}
  local t = type(val)
  if t == "table" then
    done[#done+1] = '{'
    done[#done+1] = ''
    for key, value in pairs (val) do
      if not keyignore[key] then
        done[#done+1] = '['
        plaindump(key, opts, done)
        done[#done+1] = ']='
        plaindump(value, opts, done)
        done[#done+1] = ","
      end
    end
    done[#done] = '}'
  elseif t == "string" then
    done[#done+1] = ("%q"):format(val):gsub("\010","n"):gsub("\026","\\026")
  elseif t == "number" then
    done[#done+1] = ("%.17g"):format(val)
  else
    done[#done+1] = tostring(val)
  end
  return final and table.concat(done, '')
end
```

Maybe it would make sense to integrate it and use when "simple" option is passed (or some other trigger). The main issue is that if you run it on a data structure that has loops, it will keep looping and if it has multi-refs, it will serialize those as copies, so there are definitely some trade-offs here.

**Comment by estansifer** [comment]
Thank you for your response. While the main case is a simple structure, there is no guarantee that the data has no loops or multirefs, and correctness is important, so unfortunately the slower code must be used for this application.

**Comment by tspader** [comment]
Thanks so much for posting this, even though it was 7 years ago and I'm sure a throwaway script. Serpent, while excellent, became too slow for my needs and your one off script saved me a few hours of headache rolling my own!
