### ISSUE TITLE
passing level to custom formatter as fifth parameter

### ISSUE THREAD

**Issue by cigumo** [pkulchenko/serpent#25]
currently the formatter function is: 
```function(tag,head,body,tail)```

I propose making it: 
```function(tag,head,body,tail,level)```

Maybe it's already available and I don't know how to access it. 

Thanks!

**Comment by pkulchenko** [comment]
@cigumo, do you have an example on when this may be useful?

**Comment by cigumo** [comment]
I use the level parameter to make the indentation easier. 

This is part of a serializer I wrote that adds newlines and indents only when a new class stars. (This works together with a custom sort that puts the class key first.)
```
local custom_format = function(tag,head,body,tail,level)
                          local class_body = (string.find(body,'^class'))
                          return tag..(class_body and '\n'..string.rep('    ',level) or '')..head..body..tail
                       end
```

The only change I needed to do is add the level param to custom() in this line of serpent.lua: 
```
return (custom and custom(tag,head,body,tail,level) or tag..head..body..tail)..comment(t, level)
```

Thanks.
