### ISSUE TITLE
dump/load issue with table-indexed-table

### ISSUE THREAD

**Issue by Rseding91** [pkulchenko/serpent#28]
```
local t = {};
t.save1 = nil;
t.save2 = { [{nil}] = true }

local r = {};
--t.save1 = nil;
--t.save2 = nil;
t.save1 = r;
t.save2 = { [{r}] = true }

print(serpent.dump(t))
```

Expected
`
do local _={save1={},save2={}};local __={};__._table1={nil};__._table1[1]=_.save1;_.save2[__._table1]=true;return _;end`

Actual
`
do local _={save2={},save1=nil};local __={};__._table1={{}};_.save2[__._table1]=true;_.save1=__._table1;return _;end`

If you un-comment t.save1 = nil; t.save2 = nil; it will produce the expected results.

**Comment by mpeterv** [comment]
Fixed in the referencing PR. Depending on `pairs` order there are still two valid `serpent.dump` results for that table.

If `save1` comes first:

```lua
do local _={save1={},save2={}};local __={};__._table1={nil};__._table1[1]=_.save1;_.save2[__._table1]=true;return _;end
```

If `save2` comes first:

```lua
do local _={save2={},save1=nil};local __={};__._table1={{}};_.save2[__._table1]=true;_.save1=__._table1[1];return _;end
```
