### ISSUE TITLE
call function dump 50k times in a for loop cost dozens seconds 

### ISSUE THREAD

**Issue by maverick-zhang** [pkulchenko/serpent#41]

**Comment by pkulchenko** [comment]
@maverick-zhang, why is this an issue? It depends on the data you are serializing, the hardware you are using, the options selected and many other factors. If you think the module is behaving slowly than expected, you're welcome to use a different format ([MessagePack](https://en.wikipedia.org/wiki/MessagePack) may be an option) or profile and optimize the code in this module.

**Comment by maverick-zhang** [comment]
It's weired. I have a large table and the length is about 15k. The element of the large table is nested small table. If I dump all elements  in a for loop, it costs dozens seconds. But if I dump the large table directly, it's very quick, within 1 second.

**Comment by pkulchenko** [comment]
>  If I dump all elements in a for loop, it costs dozens seconds. But if I dump the large table directly, it's very quick, within 1 second.

I think it's expected if I understand correctly what you're doing. When you say "dump all elements in a for loop" you probably have a string that you are adding the elements to in a loop, which is going to take time comparing to having strings in a table and concatenating them into one large string. serpent has some optimizations to that effect, as expanding the same string with additional fragments is going to be much slower with a large number of fragments than adding them in one pass.

If you think it's something else, I'm interested to hear what it may be.

**Comment by maverick-zhang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
         No concatenating and comparing. I should show the code earlier. It's very simple.function player.Player:writeToDBNextTickEvent()    self.eventUnnotifyQueue = {}    for idx, info in ipairs(self.eventCollectionInOneTick or {}) do     -- #self.eventCollectionInOneTick = 15k        local data = serpent.dump(info)        self.eventUnnotifyQueue[#self.eventUnnotifyQueue + 1] = data    endend-- The function above will take dozens senconds. -- And then I change the function to this:function player.Player:writeToDBNextTickEvent()    self.eventUnnotifyQueue = {}    local data = serpent.dump(self.eventCollectionInOneTick or {})    self.eventUnnotifyQueue[1] = dataend-- It's much better, within 1 second.I think it should not relate with serpent. I'm sorry to bother you. If you have the anwser, I will be very glad to hear. Thanks anyway!
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhang_sq
                            
                            
                                
                            
                    
                        
                            
                                    zhang_sq@pku.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 2/3/2021 10:11，Paul Kulchenko<notifications@github.com> wrote： 




If I dump all elements in a for loop, it costs dozens seconds. But if I dump the large table directly, it's very quick, within 1 second.

I think it's expected if I understand correctly what you're doing. When you say "dump all elements in a for loop" you probably have a string that you are adding the elements to in a loop, which is going to take time comparing to having strings in a table and concatenating them into one large string. serpent has some optimizations to that effect, as expanding the same string with additional fragments is going to be much slower with a large number of fragments than adding them in one pass.
If you think it's something else, I'm interested to hear what it may be.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pkulchenko** [comment]
I think it's similar to what I have written earlier, as you call serpent a large number of time for small fragments and in the second example it's called just once, but serializes the entire structure. I think the optimizations in the serpent handling help with this processing.
